# Generated by Django 3.2.8 on 2021-10-07 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
            ],
            options={
                'verbose_name': '市区町村',
                'verbose_name_plural': '市区町村',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='産業')),
            ],
            options={
                'verbose_name': '業種',
                'verbose_name_plural': '業種',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='職種')),
            ],
            options={
                'verbose_name': '職種',
                'verbose_name_plural': '職種',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='都道府県名')),
            ],
            options={
                'verbose_name': '都道府県',
                'verbose_name_plural': '都道府県',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='給与')),
            ],
            options={
                'verbose_name': '年収',
                'verbose_name_plural': '年収',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='タグ')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=34, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='説明文')),
                ('job_description', models.CharField(max_length=25, verbose_name='業務内容')),
                ('qualifications', models.TextField(verbose_name='応募資格')),
                ('time', models.TextField(max_length=30, verbose_name='勤務時間')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/', verbose_name='サムネイル')),
                ('img', models.FileField(upload_to='images/', verbose_name='動画')),
                ('work_style', models.CharField(choices=[('part-time', 'アルバイト'), ('permanent', '正社員'), ('temporary', '派遣社員'), ('other', 'その他')], max_length=20, verbose_name='雇用形態')),
                ('vacation', models.CharField(max_length=30, verbose_name='休日休暇')),
                ('benefit', models.TextField(verbose_name='福利厚生')),
                ('Industry', models.ManyToManyField(to='myapp.Industry', verbose_name='業種')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.city', verbose_name='市区町村')),
                ('occupation', models.ManyToManyField(to='myapp.Occupation', verbose_name='職種')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.prefecture', verbose_name='都道府県')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.salary', verbose_name='年収')),
                ('tag', models.ManyToManyField(blank=True, to='myapp.Tag', verbose_name='タグ')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.prefecture'),
        ),
    ]
